[package]
name = "rodisc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rocket = { version = "0.5.1", features = ["json"]}
tokio = "1.40.0"
serde = { version = "1", features = ["derive"]}
